### ISSUE TITLE
(Suggestion) Beeping to alert nearby players

### ISSUE THREAD

**Issue by Gnavling** [BuddyNotFound/bbv-bombs#1]
This script is amazing. I think it could add a lot to the RP if the bomb played a beeping sound or something every once in a while to alert nearby players of the bomb.

**Comment by Gameadictive** [comment]
Is not already added?

**Comment by BuddyNotFound** [comment]
there is a red flashing light, you can also easily add export to your police dispatch to alert the police for any active bombs, from there the police can alert the city and cut off the area.

**Comment by BuddyNotFound** [comment]
Beeping has been added to the script, update.

**Comment by BuddyNotFound** [comment]
Beeping has been added to the script, update.
